name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the main branch
  workflow_dispatch: # Allows manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write # Needed to push to the gh-pages branch
  # pages: write # No longer strictly needed for this deployment method
  # id-token: write # No longer strictly needed for this deployment method

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Deploy to gh-pages from @ ${{ github.sha }}
          # Keep history to avoid force pushing, which can be disruptive
          # force_orphan: true # Use this if you want a clean history on gh-pages each time
          # cname: example.com # Uncomment if you have a custom domain
